embedding_model:
  provider: "huggingface"
  model_name: "sentence-transformers/all-mpnet-base-v2"

retriever:
  top_k: 5

llm: 
  provider: "groq"
  model_name: "llama-3.1-8b-instant"
  temperature: 0
  max_output_tokens: 2048

  